common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html') ,name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/' , views.signup,name='signup'),
    path('profile/<int:user_id>/',views.profile,name='profile'),
    path('profile/<int:user_id>/userinfo/',views.userinfo,name='userinfo'),
    path('profile/<int:user_id>/dropout/',views.dropout,name='dropout'),
    path('profile/<int:user_id>/passwordchange/',views.passwordchange,name='passwordchange'),
    path('activate/<str:uid64>/<str:token>/',views.activate,name='activate'),
]

#재네릭 뷰 방식 - 함수를 직접 정의할 필요가 없음

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base_views.index,name='index'),
    path('pybo/',include('pybo.urls')),
    path('common/',include('common.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views,question_views,answer_views,comment_views,vote_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    path('', base_views.index,name='index'),
    path('board/',base_views.board,name='board'),
    path('profile/', base_views.profile, name='profile'),
    path('<int:question_id>/',base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/',answer_views.answer_create,name='answer_create'),
    path('question/create/',question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete,name='question_delete'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete,name='answer_delete'),
    path('comment/create/question/<int:question_id>/',comment_views.comment_create_question,name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',comment_views.comment_modify_question,name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',comment_views.comment_delete_question,name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),
]

pybo/models.py
from django.db import models
from common.models import myUser

#질문 모델(데이터 베이스 테이블)
class Question(models.Model):
    author = models.ForeignKey(myUser,on_delete=models.CASCADE,related_name="author_question")
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    voter = models.ManyToManyField(myUser,related_name="voter_question")
    views = models.IntegerField(default=0)


    def __str__(self):
        return self.subject

#답변 모델
class Answer(models.Model):
    #외래키 제약조건 무시하고 연쇄 삭제 됨
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(myUser, on_delete=models.CASCADE,related_name="author_answer")
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    voter = models.ManyToManyField(myUser,related_name="voter_answer")

    def __str__(self):
        return self.content

class Comment(models.Model):
    author = models.ForeignKey(myUser,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    question = models.ForeignKey(Question,null=True,blank=True,on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer,null=True,blank=True,on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from .models import Question ,Answer ,Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject','content']
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels= {
            'content' : '내용'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content':'댓글내용'
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한이 없습니다')
        return redirect('pybo:detail',question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST,instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail',question_id=answer.question.id)
    else:
        form=AnswerForm(instance=answer)
    context = {'answer' : answer , 'form': form}
    return render(request,'pybo/answer_form.html',context)

@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한이 없습니다')
        return redirect('pybo:detail',question_id=answer.question.id)
    answer.delete()
    return redirect('pybo:detail',question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


def index(request):
    return render(request,'pybo/index.html')

def profile(request):
    return render(request,'pybo/profile.html')

def board(request):
    #질문 목록
    #127.0.0.1:8000/pybo/?page=1
    page = request.GET.get('page','1')
    so = request.GET.get('so','recent')
    kw = request.GET.get('kw','')
    lc = request.GET.get('lc','10')
    qa = request.GET.get('qa','')


    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')  # '-'기호는 내림차순

    if qa =='que':
        # 유저가 작성한 글만 가져오기 구현못함
        question_list = question_list.filter(
            Q(author__id__icontains=kw)
        ).distinct()
    elif qa == 'as':
        question_list = question_list.filter(
            Q(answer__author__id__icontains=kw)
        ).distinct()
    else:
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |
                Q(content__icontains=kw) |
                Q(author__username__icontains=kw) |
                Q(answer__author__username__icontains=kw) |
                Q(answer__content__icontains=kw)
            ).distinct()

    paginator = Paginator(question_list,int(lc))
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj , 'page' : page , 'kw': kw ,'so': so , 'lc': lc}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.views += 1;
    question.save()
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Comment, Answer


@login_required(login_url='common:login')
def comment_create_question(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form' : form}
    return render(request,'pybo/comment_form.html',context)


@login_required(login_url="common:login")
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request,comment_id):
    comment = get_object_or_404(Comment,pk=comment_id)
    if request.user != comment.author:
        messages.error("댓글삭제권한이 없습니다")
        return redirect('pybo:detail',question_id=comment_id.question.id)
    comment.delete()
    return redirect('pybo:detail',question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form' : form}
    return render(request,'pybo/comment_form.html',context)


@login_required(login_url="common:login")
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request,comment_id):
    comment = get_object_or_404(Comment,pk=comment_id)
    if request.user != comment.author:
        messages.error("댓글삭제권한이 없습니다")
        return redirect('pybo:detail',question_id=comment_id.answer.question.id)
    comment.delete()
    return redirect('pybo:detail',question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    # 질문 등록
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:board')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url="common:login")
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request,'삭제권한이 없습니다')
        return redirect('pybo:detail',question_id=question.id)
    question.delete()
    return redirect('pybo:board')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if request.user == question.author:
        messages.error(request,"본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail',question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user == answer.author:
        messages.error(request,"본인이 작성한 글은 추천할 수 없습니다.")
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail',question_id=answer.question.id)

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3"> <!-- 추천영역 -->
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                 {{ question.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
               class="recommend btn btn-secondary btn-block my-1">추천</a>
            <div class="badge badge-info p-1 d-block">조회수:{{ question.views }}</div>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                    {{ question.content }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            {{ question.modify_date }}
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            {{ question.create_date }}
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri ="{% url 'pybo:question_delete' question.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}
                    <div class="mt-3 collapse" id="demo_question">
                        {% for comment in question.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space:pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }},{{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정&nbsp</a>
                            <a href="#" data-uri="{% url 'pybo:comment_delete_question' comment.id%}" class="small delete">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <a href="{% url 'pybo:comment_create_question' question.id %}"
                           class="small"><small>댓글 추가...</small></a>
                    </div>
                    <div class="mt-2">
                        <button id="mycoll_q" type="button" data-toggle="collapse" data-target="#demo_question"
                                class="btn-sm btn-primary small" ><small>댓글 보기</small></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                 {{ answer.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
               class="recommend btn btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space:pre-line;">
                        {{answer.content}}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            {{ answer.modify_date }}
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            {{ answer.create_date }}
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'pybo:answer_delete' answer.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}
                    <div class="mt-3 collapse" id="demo_answer">
                        {% for comment in answer.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space:pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }},{{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정&nbsp</a>
                            <a href="#" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}" class="small delete">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <a href="{% url 'pybo:comment_create_answer' question.id %}"
                           class="small"><small>댓글 추가...</small></a>
                    </div>
                    <div class="mt-3">
                        <button id="mycoll_a" type="button" data-toggle="collapse" data-target="#demo_answer"
                                class="btn-sm btn-primary small" ><small>댓글 보기</small></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
     {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
    {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
        <textarea name="content" id="content"
                  {% if not user.is_authenticated %} disabled {% endif %}
                  class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn btn-primary">
</form>
    <a href="{% url 'pybo:board' %}" class="btn btn-primary">목록으로</a>
</div>
{% endblock %}
{% block script %}
    <script>
        $(function(){
            $(".delete").on('click',function(){
                if(confirm("정말로 삭제하시겠습니까?")){
                    location.href = $(this).data('uri');
                }
            })
            $("#demo_question").on('show.bs.collapse',function(){
                $('#mycoll_q').html("<small>댓글 닫기</small>")

            })
            $("#demo_question").on('hide.bs.collapse',function(){
                $('#mycoll_q').html("<small>댓글 보기</small>")
            })
            $("#demo_answer").on('show.bs.collapse',function(){
                $('#mycoll_a').html("<small>댓글 닫기</small>")

            })
            $("#demo_answer").on('hide.bs.collapse',function(){
                $('#mycoll_a').html("<small>댓글 보기</small>")
            })
            $(".recommend").on('click',function(){
                if(confirm("정말로 추천하시겠습니까?")){
                    location.href = $(this).data('uri');
                }
            })
        })
    </script>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3 p-3 shadow border border-info rounded" style="background-color:white">
    <div class="row justify-content-end my-3">
        <div class="col-2 ">
            <select class="form-control so">
                <option value="recent" {% if so == "recent" %}selected{% endif %}>
                    최신순
                </option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                    추천순
                </option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>
                    인기순
                </option>
            </select>
        </div>
        <div class="col-1 ">
            <select class="form-control lc">
                <option value="5" {% if lc == "5" %}selected{% endif %}>
                    5
                </option>
                <option value="10" {% if lc == '10' %}selected{% endif %}>
                    10
                </option>
                <option value="20" {% if lc == '20' %}selected{% endif %}>
                    20
                </option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw"
                value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <form id="searchForm" method="get" action="{% url 'pybo:board' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">
        <input type="hidden" id="lc" name="lc" value="{{ lc }}">
    </form>
    <table class="table" style="table-layout:fixed">
        <thead>
            <tr class="thead-dark text-center">
                <th style="width:10%">번호</th>
                <th style="width:10%">추천</th>
                <th style="width:40%">제목</th>
                <th style="width:10%">글쓴이</th>
                <th style="width:20%">작성일</th>
                <th style="width:10%">조회수</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                {% if question.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">
                    {{ question.voter.all.count }}
                </span>
                {% endif%}
            </td>
            <td class="text-left text-truncate">
                <a href="{% url 'pybo:detail' question.id %}">{{question.subject}}
                    {% if question.answer_set.count %}
                    <sub class="text-danger small ml-2">[{{ question.answer_set.count }}]</sub>
                    {% endif %}
                </a>
            </td>
            <td><a href="{% url 'common:profile' question.author.id %}" >{{ question.author.profile.nickname }}</a></td>
            <td>{{ question.create_date }}</td>
            <td>{{ question.views }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문목록이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="#" data-page="{{ question_list.previous_page_number }}"
                   >이전
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"
                   tabindex="-1" aria-disabled="true" href="#"
                   >이전
                </a>
            </li>
        {% endif %}
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == question_list.number%}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#" data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="#" data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endfor %}
        {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="#" data-page="{{ question_list.next_page_number}}"
                   >다음
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"
                   tabindex="-1" aria-disabled="true" href="#"
                   >다음
                </a>
            </li>
        {% endif %}
    </ul>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}
{% block script%}
<script>
    $(document).ready(function(){
        $(".page-link").on('click',function(){
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });

        $("#btn_search").on('click',function(){
            $("#kw").val($(".kw").val());
            $("#page").val(1);
            $("#searchForm").submit();
        });

        $(".so").on('change',function(){
            $('#so').val($(this).val());
            $('#page').val(1);
            $('#searchForm').submit();
        })

        $(".lc").on('change',function(){
            $('#lc').val($(this).val());
            $('#page').val(1);
            $('#searchForm').submit();
        })
    });

</script>
{% endblock %}