common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html') ,name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/' , views.signup,name='signup'),
    path('profile/<int:user_id>/',views.profile,name='profile'),
    path('profile/<int:user_id>/userinfo/',views.userinfo,name='userinfo'),
    path('profile/<int:user_id>/dropout/',views.dropout,name='dropout'),
    path('profile/<int:user_id>/passwordchange/',views.passwordchange,name='passwordchange'),
    path('activate/<str:uid64>/<str:token>/',views.activate,name='activate'),
]

#재네릭 뷰 방식 - 함수를 직접 정의할 필요가 없음

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base_views.index,name='index'),
    path('pybo/',include('pybo.urls')),
    path('common/',include('common.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views,question_views,answer_views,comment_views,vote_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    path('', base_views.index,name='index'),
    path('board/',base_views.board,name='board'),
    path('profile/', base_views.profile, name='profile'),
    path('<int:question_id>/',base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/',answer_views.answer_create,name='answer_create'),
    path('question/create/',question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete,name='question_delete'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete,name='answer_delete'),
    path('comment/create/question/<int:question_id>/',comment_views.comment_create_question,name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',comment_views.comment_modify_question,name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',comment_views.comment_delete_question,name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),
]

common/models.py
import os.path

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser

class myUser(AbstractUser):
    email = models.EmailField(unique=True)
    active = models.BooleanField(default=False)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    photo = models.ImageField(blank=True,upload_to='photo/',null=True)
    nickname = models.TextField(unique=True, max_length=60)

    def delete(self, *args,**kargs):
        os.remove(os.path.join(settings.MEDIA_ROOT ,self.photo.name))
        super(Profile,self).delete(*args,**kargs)

    def photoname(self):
        return self.photo.name.split('/')[-1]



# Create your models here.

common/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

from common.models import Profile, myUser


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = myUser
        fields =("username","email")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname','photo']
        labels = {
            'nickname':'닉네임',
            'photo':'이미지'
        }

common/views.py
import os

from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password, is_password_usable
from django.contrib.auth.password_validation import validate_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.template.loader import render_to_string
from django.utils.encoding import force_text, force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from .tokens import account_activation_token

from .forms import UserForm, ProfileForm
from .models import Profile, myUser

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        Proform = ProfileForm(request.POST,request.FILES)
        if form.is_valid() and Proform.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username= username , password=raw_password)
            user.active = False;
            user.save()
            profile = Proform.save(commit=False)
            profile.user = user;
            if request.FILES:
                profile.photo = request.FILES['photo']
            profile.nickname = request.POST['nickname']
            profile.save()
            current_site = get_current_site(request)
            message = render_to_string('common/activation_email.html',{
                'user': user,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = "회원가입 인증 메일입니다."
            user_email = user.email;
            email = EmailMessage(mail_subject,message,to=[user_email])
            email.send()
            return HttpResponse(
                '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                'justify-content: center; align-items: center;">'
                '입력하신 이메일<span>로 인증링크가 전송되었습니다.</span>'
                '</div>'
            )
    else:
        form = UserForm()
        Proform = ProfileForm()
    context = {'form' : form , 'Proform':Proform}
    return render(request,'common/signup.html',context)

@login_required(login_url='common:login')
def profile(request,user_id):
    user = myUser.objects.get(id=user_id)
    question_list = user.author_question.all().order_by('-create_date')
    answer_list = user.author_answer.all().order_by('-create_date')
    context = {'question_list':question_list , 'answer_list':answer_list , 'profile' :user.profile}
    return render(request,'common/profile.html',context)

@login_required(login_url='common:login')
def userinfo(request,user_id):
    user = myUser.objects.get(id=user_id)
    if request.method == "POST":
        profile_form = ProfileForm(request.POST)
        if request.FILES:
            if user.profile.photo:
                os.remove(os.path.join(settings.MEDIA_ROOT, user.profile.photo.path))
            user.profile.photo = request.FILES['photo']
            user.profile.save()
        if profile_form.is_valid():
            myprofile = profile_form.save(commit=False)
            user.profile.nickname = myprofile.nickname
            messages.add_message(request,messages.SUCCESS,"닉네임이 수정되었습니다")
            user.profile.save()
            return redirect('common:userinfo',user_id)
    else:
        profile_form = ProfileForm(instance=user.profile)
    context = {'form' : profile_form ,'profile':user.profile }
    return render(request,'common/userinfo.html',context)

@login_required(login_url='common:login')
def dropout(request,user_id):
    user = myUser.objects.get(id=user_id)
    if request.user.is_authenticated:
        logout(request)
    user.profile.delete()
    user.delete()
    return redirect('index')

@login_required(login_url='common:login')
def passwordchange(request,user_id):
    user = myUser.objects.get(id=user_id)
    if request.method == 'POST':
        now_password = request.POST['now_password']
        if check_password(now_password,user.password):
            new_password = request.POST['password1']
            confirm_password = request.POST['password2']
            try:
                validate_password(new_password)
                validate_password(confirm_password)
            except ValidationError as e:
                context = {'profile': user.profile ,'errors':e}
                return render(request,'common/passwordchange.html',context)
            if new_password == confirm_password:
                user.set_password(new_password)
                update_session_auth_hash(request,user)
                user.save()
                messages.success(request,"비밀번호가 정상적으로 변경되었습니다")
                return redirect('common:passwordchange',user_id)
            else:
                messages.warning(request,"새로운 비밀번호를 확인해주세요")
        else:
            messages.warning(request, "현재 비밀번호를 확인해주세요")

    context = {'profile': user.profile}
    return render(request,'common/passwordchange.html',context)

def activate(request,uid64,token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        user = myUser.objects.get(pk=uid)
    except(TypeError,ValueError,OverflowError,myUser.DoseNotExsit):
        user = None;
    if user is not None and account_activation_token.check_token(user,token):
        user.active = True
        user.save()
        auth.login(request,user)
        return redirect("index")
    else:
        return render(request,'index')

templates/common/activation_email.html
{% autoescape off %}

    {{user.username}}님, 아래 링크를 클릭하여 계정을 활성화하세요:
    http://{{domain}}{% url 'common:activate' uid64=uid token=token %}

{% endautoescape %}

templates/common/drop_out.html
<div class="modal fade" id="drop_out" tabindex="-1" aria-labelledby="drop_out_Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger" id="drop_out_Label">회원 탈퇴</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       정말로 회원 탈퇴하시겠습니까?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">아닙니다</button>
        <button type="button" class="btn btn-danger drop">탈퇴합니다</button>
      </div>
    </div>
  </div>
</div>

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login'%}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value | default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-secondary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/passwordchange.html
{% extends 'common/profilebase.html' %}
{% block box %}
            <form class="card-body" method="post">
                {% csrf_token %}
                <div class="border border-primary rounded w-50 my-3" >
                    <div class="form-group p-3 m-3 rounded" style="border:4px solid #0422">
                        <label for="now_password" >현재 패스워드</label>
                        <input type="password" class="form-control" id="now_password" name="now_password"
                            value="">
                    </div>
                </div>
                <div class="border border-primary rounded w-50 my-3" >
                    <div class="form-group p-3 m-3 rounded" style="border:4px solid #0422">
                        <label for="password1" >변경 패스워드</label>
                        <input type="password" class="form-control" id="password1" name="password1"
                            value="">
                    </div>
                </div>
                <div class="border border-primary rounded w-50 my-3">
                    <div class="form-group p-3 m-3" style="border:4px solid #0422">
                        <label for="password2">변경 패스워드 확인</label>
                        <input type="password" class="form-control" id="password2" name="password2"
                        value="">
                    </div>
                </div>
                <button type="submit" class="btn btn-secondary mt-3 float-right">변경</button>
            </form>
{% endblock %}

templates/common/profile.html
{% extends 'common/profilebase.html' %}
{% block box %}
            <div>
                <ul class="list-unstyled"><h3 class="card-title my-4">질문목록</h3>
                {% for question in question_list %}
                    {% if forloop.counter0 < 3 %}
                    <li class="d-flex row">
                        <div class="col-8 text-truncate">
                            <a href="{% url 'pybo:detail' question.id %}">
                                {{question.subject}}
                            </a>
                        </div>
                        <div class="text-right">{{question.create_date}}</div>
                    </li>
                    {% endif %}
                {% endfor %}
                {% if question_list.count >= 3%}
                    <li class="small mt-2 more"><a href="#" class="btn" id="que">
                        더 보기...
                    </a></li>
                {% endif %}
                </ul>
            </div>
            <div>
                <ul class="list-unstyled"><h3 class="card-title my-4">답변목록</h3>
                {% for answer in answer_list %}
                    {% if forloop.counter0 < 3 %}
                    <li class="d-flex row">
                        <div class="col-8 text-truncate">
                            <a href="{% url 'pybo:detail' answer.id %}">
                                {{answer.content}}
                            </a>
                        </div>
                        <div class="text-right">{{answer.create_date}}</div>
                    </li>
                    {% endif %}
                {% endfor %}
                {% if answer_list.count >= 3 %}
                    <li class="small mt-2 more"><a href="#" class="btn" id="as">
                        더 보기...
                    </a></li>
                {% endif %}
                </ul>
            </div>
{% endblock %}

templates/common/profilebase.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container mx-auto" style="margin:7rem">
    {% include 'form_errors.html' %}
    <form id="searchForm" method="get" action="{% url 'pybo:board' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="qa" name="qa" value="">
    </form>
    <div class="row">
<!--        유저 정보-->
        <div class="col-4 card">
            {%if profile.photo %}
            <img src="{{ profile.photo.url }}" class="card-top-img img-thumbnail w-75 profile-img" style="margin:auto ;">
            {% else %}
            <img src="{% static 'people/noimg.jpg' %}" class="card-top-img img-thumbnail" style="margin:auto">
            {% endif %}
            <ul class="list-group my-3">
                <li class="list-group-item"><a href="#">질문&답변</a></li>
                {% if profile.user.id == user.id %}
                <li class="list-group-item"><a href="{% url 'common:userinfo' profile.user.id %}" >개인정보</a></li>
                <li class="list-group-item"><a href="{% url 'common:passwordchange' profile.user.id %}">비밀번호 수정</a></li>
                <li class="list-group-item"><a href="#" class="text-danger" data-toggle="modal" data-target="#drop_out">회원탈퇴</a></li>
                {% endif %}
            </ul>
        </div>
        {% include 'common/drop_out.html' %}
<!--        질문 & 답변 목록-->
        <div class="col-8 card">
            {% block box %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        $("#more").on('click',function(){
            $("#kw").val({{ user_id }});
            if($(this).attr('id') == "que")
                $("#qa").val("que")
            else
                $("#qa").val("as")
            $("#searchForm").submit();
        })
        $('.drop').on('click',function(){
            location.href="{% url 'common:dropout' profile.user.id %}"
        })
    })
</script>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <div class="row my-3">
    <div class="col-4 border-bottom">
      <h4>회원가입</h4>
    </div>
    <div class="col-8 text-right">
      <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a></span>
    </div>
  </div>
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token%}
    {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="username">아이디</label>
      <input type="text" class="form-control" name="username" id="username"
        value="{{ form.username.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="nickname">닉네임</label>
      <input type="text" class="form-control" name="nickname" id="nickname"
        value="{{ Proform.nickname.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input type="password" class="form-control" name="password1" id="password1"
        value="{{ form.password1.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="password2">비밀번호 확인</label>
      <input type="password" class="form-control" name="password2" id="password2"
        value="{{ form.password2.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="email">이메일</label>
      <input type="email" class="form-control" name="email" id="email"
        value="{{ form.email.value | default_if_none:'' }}">
    </div>
    <div class="w-25">
      <label for="photo">이미지</label>
      <input type="file" name="photo" id="photo" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary my-3">생성하기</button>
  </form>
</div>
{% endblock %}

templates/common/userinfo.html
{% extends 'common/profilebase.html' %}
{% block box %}
            <form class="card-body" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="border border-primary rounded w-50 my-3" >
                    <div class="form-group p-3 m-3 rounded" style="border:4px solid #0422">
                        <label for="nickname">닉네임</label>
                        <input type="text" class="form-control" id="nickname" name="nickname"
                            value="{{ form.nickname.value }}">
                    </div>
                </div>
                <div class="border border-primary rounded w-50 my-3">
                    <div class="form-group p-3 m-3" style="border:4px solid #0422">
                        <label for="photo">이미지</label>
                        <input type="file" class="form-control-file" id="photo" name="photo" multiple>
                        {%if profile.photo %}
                        {{profile.photoname}}
                        {% endif%}
                    </div>
                </div>
                <button type="submit" class="btn btn-secondary mt-3 float-right">변경</button>
            </form>
{% endblock %}