common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html') ,name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/' , views.signup,name='signup'),
    path('profile/<int:user_id>/',views.profile,name='profile'),
    path('profile/<int:user_id>/userinfo/',views.userinfo,name='userinfo'),
    path('profile/<int:user_id>/dropout/',views.dropout,name='dropout'),
    path('profile/<int:user_id>/passwordchange/',views.passwordchange,name='passwordchange'),
    path('activate/<str:uid64>/<str:token>/',views.activate,name='activate'),
]

#재네릭 뷰 방식 - 함수를 직접 정의할 필요가 없음

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base_views.index,name='index'),
    path('pybo/',include('pybo.urls')),
    path('common/',include('common.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views,question_views,answer_views,comment_views,vote_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    path('', base_views.index,name='index'),
    path('board/',base_views.board,name='board'),
    path('profile/', base_views.profile, name='profile'),
    path('<int:question_id>/',base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/',answer_views.answer_create,name='answer_create'),
    path('question/create/',question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete,name='question_delete'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify,name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete,name='answer_delete'),
    path('comment/create/question/<int:question_id>/',comment_views.comment_create_question,name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',comment_views.comment_modify_question,name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',comment_views.comment_delete_question,name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


def index(request):
    return render(request,'pybo/index.html')

def profile(request):
    return render(request,'pybo/profile.html')

def board(request):
    #질문 목록
    #127.0.0.1:8000/pybo/?page=1
    page = request.GET.get('page','1')
    so = request.GET.get('so','recent')
    kw = request.GET.get('kw','')
    lc = request.GET.get('lc','10')
    qa = request.GET.get('qa','')


    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')  # '-'기호는 내림차순

    if qa =='que':
        # 유저가 작성한 글만 가져오기 구현못함
        question_list = question_list.filter(
            Q(author__id__icontains=kw)
        ).distinct()
    elif qa == 'as':
        question_list = question_list.filter(
            Q(answer__author__id__icontains=kw)
        ).distinct()
    else:
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |
                Q(content__icontains=kw) |
                Q(author__username__icontains=kw) |
                Q(answer__author__username__icontains=kw) |
                Q(answer__content__icontains=kw)
            ).distinct()

    paginator = Paginator(question_list,int(lc))
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj , 'page' : page , 'kw': kw ,'so': so , 'lc': lc}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.views += 1;
    question.save()
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
    {% block style %}
    {% endblock %}
    </style>
    <link rel="stylesheet"  href="{% static 'pybo/css/bootstrap.css' %}">
    <link rel="stylesheet"  href="{% static 'pybo/css/style.css' %}">
    <title>Hello~py</title>
</head>
<body style="background-color:#F4FFFF">
{% include 'navbar.html' %}
<!--기본 템플릿 안에 삽입될 내용 start -->

{% block content %}
{% endblock %}
<script src="{% static 'pybo/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'pybo/js/bootstrap.js' %}"></script>
<!--기본 템플릿 안에 삽입될 내용 end -->
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}  <!-- 필드 오류 -->
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}
{% if Proform.errors %}  <!-- 필드 오류 -->
  {% for field in Proform %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in Proform.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        <strong>{{ message.message }}</strong>
      </div>
    {% endfor %}
{% endif%}
{% if errors %}
    {% for error in errors %}
      <div class="alert alert-danger">
        <strong>{{ error }}</strong>
      </div>
    {% endfor %}
{% endif%}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">게시판페이지</a>
    <button class ="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:profile' user.id %}"><span class="font-weight-bold">{{user.profile.nickname}}</span>님 페이지</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:signup' %}">회원 가입</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pybo:board' %}">질문/답변</a>
            </li>
        </ul>
    </div>
</nav>